# Site settings
title: Be Mobile Wellness
sub_title: Where Corporate and Wellness Unite!
email: Vanessa@BeMobileWellness.com
phone_number: '(650) 516-7441'
url: https://BeMobileWellness.github.io
description: "Be Mobile Wellness offers various services to corporate and private clients such as Massage, Yoga, and Stand-Up Paddleboard (SUP)."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Be Mobile Wellness
shop_link: "https://squareup.com/market/be-mobile-wellness"
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Anat0myNerd
  - title: facebook
    url: https://www.facebook.com/BeMobileWellness
  - title: linkedin
    url: https://linkedin.com/in/vanessaragains
  - title: 'google-plus'
    url: https://google.com/+VanessaRagains
  - title: instagram
    url: https://instagram.com/be_mobile_wellness
  - title: youtube
    url: 'https://www.youtube.com/c/VanessaRagains'

# Build settings
markdown: kramdown
permalink: pretty
