# Site settings
title: Anatomy Nerd Lifestyle Coaching
sub_title: When you invest in your employees' health, you invest in your cpmapny's wealth!
email: TheAnatomyNerd@gmail.com
url: http://BeMobileWellness.com
description: "Join my movement creating a healthy workplace culture with on-site massage and the Anatomy Nerd community."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

sign_up_video:
  enabled: false
  title: Sign-up video
  url: https://www.youtube.com/embed/P7rFPeSrAYI

vagaro_popup_script: https://www.vagaro.com//resources/WidgetPopupLoader/OZqnCJ0rCJCcT3qrV3Py79oz34mC2PlFLblPs4WGsnXStCcTpqp9d0ygZawifCs7fo?v=EjAuv9MpNo2XUPbZ9g0szNpz9w39GXWvc8x4VdYZMAL#

slideshow:
  images: '["img/intro-bg.jpg", "img/home-slideshow-2.jpg", "img/home-slideshow-3.jpg"]'
  delay: 7000

now_hiring:
  video:
    enabled: false
    url: https://player.vimeo.com/video/262857964

# Footer settings
footer: Be Mobile Wellness
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/TheAnatomyNerd/
  - title: linkedin
    url: https://linkedin.com/in/vanessaragains
  - title: instagram
    url: https://www.instagram.com/theanatomynerd/

# The ribbon in ribbon.html will be rendered when this is true
# Set to false to remove the ribbon
ribbon:
  enabled: false
  text: Download Our App!
  link: http://mndbdy.ly/e/192309

podcast:
  link: https://anchor.fm/theanatomynerdshow
  text: Podcast


# Build settings
markdown: kramdown
permalink: pretty
