# Site settings
title: Be Mobile Wellness
sub_title: Redefining the Direction of Corporate & Personal Wellness!
email: support@BeMobileWellness.com
phone_number: '(650) 516-7441'
url: http://BeMobileWellness.com
description: "Be Mobile Wellness offers various services to corporate and private clients such as Massage, Yoga, and Stand-Up Paddleboard (SUP)."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

sign_up_video:
  enabled: false
  title: Sign-up video
  url: https://www.youtube.com/embed/P7rFPeSrAYI

# Footer settings
footer: Be Mobile Wellness
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/BeMobileWellness
  - title: linkedin
    url: https://linkedin.com/in/vanessaragains
  - title: 'google-plus'
    url: https://google.com/+VanessaRagains
  - title: instagram
    url: https://instagram.com/be_mobile_wellness
  - title: youtube
    url: 'https://www.youtube.com/c/VanessaRagains'

# The ribbon in ribbon.html will be rendered when this is true
# Set to false to remove the ribbon
ribbon:
  enabled: false
  text: Download Our App!
  link: http://mndbdy.ly/e/192309


# Build settings
markdown: kramdown
permalink: pretty
