# Site settings
title: Be Mobile Wellness
sub_title: Redefining the Standard of Corporate Wellness!
email: support@BeMobileWellness.com
phone_number: '(650) 516-7441'
url: http://BeMobileWellness.com
description: "Be Mobile Wellness offers on-site Corporate Wellness services such as Table Massage, Yoga, and Fitness Coahcing."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

sign_up_video:
  enabled: false
  title: Sign-up video
  url: https://www.youtube.com/embed/P7rFPeSrAYI

vagaro_popup_script: https://www.vagaro.com//resources/WidgetPopupLoader/OZqnCJ0rCJCcT3qmV35y6RuQlXiz3avV34mC2PlFLDbSdPfOsLp9dSycPCu7gevEhAJDXwQ0?v=syBdFF12pfvsGLlyNMFog7iYZAeY5j15frm5uzKyES20#

slideshow:
  images: '["img/intro-bg.jpg", "img/home-slideshow-2.jpg", "img/home-slideshow-3.jpg"]'
  delay: 7000

now_hiring:
  video:
    enabled: false
    url: https://player.vimeo.com/video/262857964

# Footer settings
footer: Be Mobile Wellness
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/BeMobileWellness
  - title: linkedin
    url: https://linkedin.com/in/vanessaragains
  - title: instagram
    url: https://instagram.com/be_mobile_wellness

# The ribbon in ribbon.html will be rendered when this is true
# Set to false to remove the ribbon
ribbon:
  enabled: false
  text: Download Our App!
  link: http://mndbdy.ly/e/192309


# Build settings
markdown: kramdown
permalink: pretty
